# Generated by Django 4.2 on 2024-02-28 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_category_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='directory.category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_time'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is_active'),
        ),
        migrations.AlterField(
            model_name='category',
            name='logo',
            field=models.ImageField(upload_to='categories/', verbose_name='logo'),
        ),
        migrations.AlterField(
            model_name='category',
            name='modified_time',
            field=models.DateTimeField(auto_now=True, verbose_name='modified_time'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=31, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='directory',
            name='categories',
            field=models.ManyToManyField(to='directory.category', verbose_name='Categories'),
        ),
        migrations.AlterField(
            model_name='directory',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_time'),
        ),
        migrations.AlterField(
            model_name='directory',
            name='description',
            field=models.CharField(max_length=511, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='directory',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is_active'),
        ),
        migrations.AlterField(
            model_name='directory',
            name='link',
            field=models.CharField(max_length=127, verbose_name='link'),
        ),
        migrations.AlterField(
            model_name='directory',
            name='logo',
            field=models.ImageField(upload_to='directories/', verbose_name='logo'),
        ),
        migrations.AlterField(
            model_name='directory',
            name='modified_time',
            field=models.DateTimeField(auto_now=True, verbose_name='modified_time'),
        ),
        migrations.AlterField(
            model_name='directory',
            name='name',
            field=models.CharField(max_length=63, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='directory',
            name='slug',
            field=models.CharField(max_length=31, unique=True, verbose_name='slug'),
        ),
    ]
